In [41]:

import numpy as np
x=np.mat([[1,2,3],[4,5,6],[7,8,9]])
y=np.mat([[10,12,13],[14,15,16],[12,13,14]])

In [42]:
#1.Write a Python Program to Add Two Matrices?
np.add(x,y)

matrix([[11, 14, 16],
        [18, 20, 22],
        [19, 21, 23]])

In [43]:
#2.Write a Python Program to Multiply Two Matrices?
x*y

matrix([[ 74,  81,  87],
        [182, 201, 216],
        [290, 321, 345]])

In [44]:
#3.Write a Python Program to Transpose a Matrix?
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [45]:
np.transpose(x)

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [54]:
#4.Write a Python Program to Sort Words in Alphabetic Order?
s="i am writing a program to sort words in alphabetical order"
l=s.split(" ")
l.sort()

print(" ".join(l))

a alphabetical am i in order program sort to words writing


In [59]:
#5.Write a Python Program to Remove Punctuation From a String?
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
s1="The student's job was to make su@re no on-e touched the pe%t rabb>it's brea?kfast."
s2=""
for i in s1:
    if i in punctuations:
        continue
    
    else:
        s2=s2+i
    
s2

'The students job was to make sure no one touched the pet rabbits breakfast'